USE omelete_db;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Jobs;


CREATE TABLE users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(240) NOT NULL,
    email VARCHAR(240) NOT NULL,
    password VARCHAR(240) NOT NULL,
    rest_name VARCHAR(500) NOT NULL,
    rest_cat VARCHAR(400) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE jobs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    title VARCHAR(240) NOT NULL,
    description TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    PRIMARY KEY (id)
);



